services:

  mysql-service:
    image: mysql:latest
    container_name: mysql-container
    networks:
      - compose-bridge
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dictionary_api_database
      MYSQL_USER: spring_boot
      MYSQL_PASSWORD: Leonardodev@
    ports:
      - 3306:3306

  redis-service:
    image: redis:latest
    container_name: redis-container
    networks:
      - compose-bridge
    ports:
      - 6379:6379

  dictionary_api:
    image: dictionary_api:1.0
    networks:
      - compose-bridge
    ports:
      - 8080:8080
    depends_on:
      - mysql-service
      - redis-service

networks:
  compose-bridge:
    driver: bridge
