services:

  mysql-service:
    image: mysql:latest
    container_name: mysql-container
    networks:
      - compose-bridge
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dictionary_api_database
      MYSQL_USER: spring_boot
      MYSQL_PASSWORD: Leonardodev@
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/mysql --user=root --password=root --execute 'SHOW DATABASES;'"]
      interval: 2s
      timeout: 20s
      retries: 10

  redis-service:
    image: redis:latest
    container_name: redis-container
    networks:
      - compose-bridge
    ports:
      - 6379:6379

  dictionary_api:
    image: dictionary_api:1.0
    container_name: dictionary_api
    networks:
      - compose-bridge
    ports:
      - 8080:8080
    depends_on:
      mysql-service:
        condition: service_healthy
      redis-service:
        condition: service_started
    restart: on-failure

networks:
  compose-bridge:
    driver: bridge
